# Generated by Django 2.0.7 on 2018-07-14 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Approved'), (2, 'Rejected')])),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Rejected')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contribution_requests', models.ManyToManyField(related_name='contrib_requested_issues', through='main_app.ContributionRequest', to=settings.AUTH_USER_MODEL)),
                ('down_votes', models.ManyToManyField(related_name='down_vote_issues', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='main_app.Tag')),
                ('up_votes', models.ManyToManyField(related_name='up_vote_issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contributionrequest',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Issue'),
        ),
    ]
